function plots = plotFeatures()

plots = figure('Name','figures/pitchProfiles')
subplot(1,3,1), plot(featureMatrix1(1,:)) 
ylabel('Frequency [Hz]')
xlabel('Window')
set(gca, 'YScale', 'log')
title('Melody 1')
subplot(1,3,2), plot(featureMatrix2(1,:))
ylabel('Frequency [Hz]')
xlabel('Window')
set(gca, 'YScale', 'log')
title('Melody 2')
subplot(1,3,3), plot(featureMatrix3(1,:))
ylabel('Frequency [Hz]')
xlabel('Window')
set(gca, 'YScale', 'log')
title('Melody 3')